if(NOT DEFINED OBJECTS_FILE OR NOT DEFINED TEXT_FILE OR NOT DEFINED COLLISION_FILE OR NOT DEFINED HEADER_FILE OR NOT DEFINED OUTPUT)
  message(FATAL_ERROR "OBJECTS_FILE, TEXT_FILE, COLLISION_FILE, HEADER_FILE, and OUTPUT must be provided")
endif()

file(STRINGS "${OBJECTS_FILE}" OBJECT_LINES)
file(STRINGS "${TEXT_FILE}" TEXT_LINES)
file(STRINGS "${COLLISION_FILE}" COLLISION_LINES)
file(STRINGS "${HEADER_FILE}" HEADER_LINES)

set(PAGE_BREAK_MARKER "<PAGE_BREAK>")

function(escape_cpp out value)
  set(text "${value}")
  string(REPLACE "\\" "\\\\" text "${text}")
  string(REPLACE "\"" "\\\"" text "${text}")
  string(REPLACE "${PAGE_BREAK_MARKER}" "\\f" text "${text}")
  string(REPLACE "\n" "\\n" text "${text}")
  set(${out} "${text}" PARENT_SCOPE)
endfunction()

function(try_map_to_world_id out supported constant_name)
  if(constant_name STREQUAL "PALLET_TOWN")
    set(${out} "pokered::WorldId::PalletTown" PARENT_SCOPE)
    set(${supported} TRUE PARENT_SCOPE)
  elseif(constant_name STREQUAL "ROUTE_1")
    set(${out} "pokered::WorldId::Route1" PARENT_SCOPE)
    set(${supported} TRUE PARENT_SCOPE)
  else()
    set(${out} "" PARENT_SCOPE)
    set(${supported} FALSE PARENT_SCOPE)
  endif()
endfunction()

function(message_id_from_text out text_constant)
  if(text_constant STREQUAL "TEXT_ROUTE1_YOUNGSTER1")
    set(${out} "pokered::MessageId::Route1Youngster1" PARENT_SCOPE)
  elseif(text_constant STREQUAL "TEXT_ROUTE1_YOUNGSTER2")
    set(${out} "pokered::MessageId::Route1Youngster2" PARENT_SCOPE)
  elseif(text_constant STREQUAL "TEXT_ROUTE1_SIGN")
    set(${out} "pokered::MessageId::Route1Sign" PARENT_SCOPE)
  else()
    message(FATAL_ERROR "Unsupported text constant ${text_constant}")
  endif()
endfunction()

function(normalize_facing out facing_token)
  if(facing_token STREQUAL "UP")
    set(value "pokered::Facing::Up")
  elseif(facing_token STREQUAL "DOWN")
    set(value "pokered::Facing::Down")
  elseif(facing_token STREQUAL "LEFT")
    set(value "pokered::Facing::Left")
  elseif(facing_token STREQUAL "RIGHT")
    set(value "pokered::Facing::Right")
  elseif(facing_token STREQUAL "UP_DOWN" OR facing_token STREQUAL "NONE" OR facing_token STREQUAL "ANY_DIR")
    set(value "pokered::Facing::Down")
  elseif(facing_token STREQUAL "LEFT_RIGHT")
    set(value "pokered::Facing::Left")
  else()
    message(FATAL_ERROR "Unsupported facing token ${facing_token}")
  endif()
  set(${out} "${value}" PARENT_SCOPE)
endfunction()

function(normalize_connection_direction out direction_token)
  if(direction_token STREQUAL "north")
    set(value "pokered::Facing::Up")
  elseif(direction_token STREQUAL "south")
    set(value "pokered::Facing::Down")
  elseif(direction_token STREQUAL "west")
    set(value "pokered::Facing::Left")
  elseif(direction_token STREQUAL "east")
    set(value "pokered::Facing::Right")
  else()
    message(FATAL_ERROR "Unsupported connection direction ${direction_token}")
  endif()
  set(${out} "${value}" PARENT_SCOPE)
endfunction()

set(BORDER_BLOCK "0x00")
set(WARP_COUNT 0)
set(BG_EVENT_COUNT 0)
set(NPC_COUNT 0)
set(CONNECTION_COUNT 0)
set(COLLISION_TILE_COUNT 0)
set(WARPS "")
set(BG_EVENTS "")
set(NPCS "")
set(CONNECTIONS "")
set(COLLISION_TILES "")

foreach(raw_line IN LISTS HEADER_LINES)
  string(STRIP "${raw_line}" line)
  if(line MATCHES "^connection[ \t]+(north|south|west|east),[ \t]*[A-Za-z0-9_]+,[ \t]*([A-Z0-9_]+),[ \t]*(-?[0-9]+)")
    try_map_to_world_id(target_world_id supported "${CMAKE_MATCH_2}")
    if(supported)
      normalize_connection_direction(direction "${CMAKE_MATCH_1}")
      string(APPEND CONNECTIONS "    {${direction}, ${target_world_id}, ${CMAKE_MATCH_3}},\n")
      math(EXPR CONNECTION_COUNT "${CONNECTION_COUNT} + 1")
    endif()
  endif()
endforeach()

foreach(raw_line IN LISTS OBJECT_LINES)
  string(STRIP "${raw_line}" line)
  if(line MATCHES "^db \\$([0-9A-Fa-f]+)")
    string(TOUPPER "${CMAKE_MATCH_1}" border_hex)
    set(BORDER_BLOCK "0x${border_hex}")
  elseif(line MATCHES "^warp_event[ \t]+([0-9]+),[ \t]*([0-9]+),[ \t]*([A-Z0-9_]+),[ \t]*([0-9]+)")
    try_map_to_world_id(target_world_id supported "${CMAKE_MATCH_3}")
    if(NOT supported)
      message(FATAL_ERROR "Unsupported warp destination ${CMAKE_MATCH_3}")
    endif()
    string(APPEND WARPS
           "    {${CMAKE_MATCH_1}, ${CMAKE_MATCH_2}, false, ${target_world_id}, ${CMAKE_MATCH_4}},\n")
    math(EXPR WARP_COUNT "${WARP_COUNT} + 1")
  elseif(line MATCHES "^bg_event[ \t]+([0-9]+),[ \t]*([0-9]+),[ \t]*(TEXT_[A-Z0-9_]+)")
    message_id_from_text(message_id "${CMAKE_MATCH_3}")
    string(APPEND BG_EVENTS "    {${CMAKE_MATCH_1}, ${CMAKE_MATCH_2}, ${message_id}},\n")
    math(EXPR BG_EVENT_COUNT "${BG_EVENT_COUNT} + 1")
  elseif(line MATCHES "^object_event[ \t]+([0-9]+),[ \t]*([0-9]+),[ \t]*SPRITE_[A-Z0-9_]+,[ \t]*[A-Z]+,[ \t]*([A-Z_]+),[ \t]*(TEXT_[A-Z0-9_]+)")
    normalize_facing(facing "${CMAKE_MATCH_3}")
    message_id_from_text(message_id "${CMAKE_MATCH_4}")
    string(APPEND NPCS "    {${CMAKE_MATCH_1}, ${CMAKE_MATCH_2}, ${facing}, ${message_id}},\n")
    math(EXPR NPC_COUNT "${NPC_COUNT} + 1")
  endif()
endforeach()

set(IN_OVERWORLD_COLL FALSE)
foreach(raw_line IN LISTS COLLISION_LINES)
  string(STRIP "${raw_line}" line)
  if(line STREQUAL "Overworld_Coll::")
    set(IN_OVERWORLD_COLL TRUE)
  elseif(IN_OVERWORLD_COLL AND line MATCHES "^coll_tiles")
    string(REGEX MATCHALL "\\$[0-9A-Fa-f][0-9A-Fa-f]" collision_matches "${line}")
    foreach(match IN LISTS collision_matches)
      string(SUBSTRING "${match}" 1 2 collision_hex)
      string(TOUPPER "${collision_hex}" collision_hex)
      string(APPEND COLLISION_TILES "    0x${collision_hex},\n")
      math(EXPR COLLISION_TILE_COUNT "${COLLISION_TILE_COUNT} + 1")
    endforeach()
    set(IN_OVERWORLD_COLL FALSE)
  endif()
endforeach()

if(COLLISION_TILE_COUNT EQUAL 0)
  message(FATAL_ERROR "Failed to parse Overworld collision tiles from ${COLLISION_FILE}")
endif()

set(CURRENT_NAME "")
set(CURRENT_TEXT "")
set(MESSAGE_NAMES "")

foreach(raw_line IN LISTS TEXT_LINES)
  string(STRIP "${raw_line}" line)
  if(line MATCHES "^_([A-Za-z0-9_]+)::")
    set(CURRENT_NAME "${CMAKE_MATCH_1}")
    set(CURRENT_TEXT "")
  elseif(line MATCHES "^(text|line|cont|para) \"(.*)\"$")
    set(command_name "${CMAKE_MATCH_1}")
    set(chunk "${CMAKE_MATCH_2}")
    if(command_name STREQUAL "text")
      if(CURRENT_TEXT STREQUAL "")
        set(CURRENT_TEXT "${chunk}")
      else()
        string(APPEND CURRENT_TEXT "${chunk}")
      endif()
    elseif(command_name STREQUAL "para")
      string(APPEND CURRENT_TEXT "${PAGE_BREAK_MARKER}${chunk}")
    else()
      string(APPEND CURRENT_TEXT "\n${chunk}")
    endif()
  elseif(line STREQUAL "done" OR line STREQUAL "prompt" OR line STREQUAL "text_end")
    if(NOT CURRENT_NAME STREQUAL "")
      string(REPLACE "<PLAYER>" "PLAYER" CURRENT_TEXT "${CURRENT_TEXT}")
      string(REPLACE "<RIVAL>" "RIVAL" CURRENT_TEXT "${CURRENT_TEXT}")
      list(APPEND MESSAGE_NAMES "${CURRENT_NAME}")
      set("TEXT_${CURRENT_NAME}" "${CURRENT_TEXT}")
      set(CURRENT_NAME "")
      set(CURRENT_TEXT "")
    endif()
  endif()
endforeach()

file(WRITE "${OUTPUT}" "#pragma once\n\n#include <array>\n#include <cstdint>\n#include <string_view>\n\n#include \"pokered/world/map_data.hpp\"\n\nnamespace generated {\ninline constexpr std::uint8_t kRoute1BorderBlock = ${BORDER_BLOCK};\ninline constexpr std::array<pokered::Warp, ${WARP_COUNT}> kRoute1Warps = {{\n${WARPS}}};\ninline constexpr std::array<pokered::BgEvent, ${BG_EVENT_COUNT}> kRoute1BgEvents = {{\n${BG_EVENTS}}};\ninline constexpr std::array<pokered::Npc, ${NPC_COUNT}> kRoute1Npcs = {{\n${NPCS}}};\ninline constexpr std::array<pokered::MapConnection, ${CONNECTION_COUNT}> kRoute1Connections = {{\n${CONNECTIONS}}};\ninline constexpr std::array<std::uint8_t, ${COLLISION_TILE_COUNT}> kRoute1CollisionTiles = {{\n${COLLISION_TILES}}};\n")

foreach(message_name IN LISTS MESSAGE_NAMES)
  escape_cpp(escaped_text "${TEXT_${message_name}}")
  file(APPEND "${OUTPUT}" "inline constexpr std::string_view k${message_name} = \"${escaped_text}\";\n")
endforeach()

file(APPEND "${OUTPUT}" "}  // namespace generated\n")
