if(NOT DEFINED OBJECTS_FILE OR NOT DEFINED TEXT_FILE OR NOT DEFINED COLLISION_FILE OR NOT DEFINED OUTPUT)
  message(FATAL_ERROR "OBJECTS_FILE, TEXT_FILE, COLLISION_FILE, and OUTPUT must be provided")
endif()

file(STRINGS "${OBJECTS_FILE}" OBJECT_LINES)
file(STRINGS "${TEXT_FILE}" TEXT_LINES)
file(STRINGS "${COLLISION_FILE}" COLLISION_LINES)

set(PAGE_BREAK_MARKER "<PAGE_BREAK>")

function(escape_cpp out value)
  set(text "${value}")
  string(REPLACE "\\" "\\\\" text "${text}")
  string(REPLACE "\"" "\\\"" text "${text}")
  string(REPLACE "${PAGE_BREAK_MARKER}" "\\f" text "${text}")
  string(REPLACE "\n" "\\n" text "${text}")
  set(${out} "${text}" PARENT_SCOPE)
endfunction()

set(BORDER_BLOCK "0x00")
set(WARP_COUNT 0)
set(BG_EVENT_COUNT 0)
set(NPC_COUNT 0)
set(COLLISION_TILE_COUNT 0)
set(WARPS "")
set(BG_EVENTS "")
set(NPCS "")
set(COLLISION_TILES "")

function(map_to_world_id out constant_name)
  if(constant_name STREQUAL "REDS_HOUSE_1F")
    set(${out} "pokered::WorldId::RedsHouse1F" PARENT_SCOPE)
  elseif(constant_name STREQUAL "REDS_HOUSE_2F")
    set(${out} "pokered::WorldId::RedsHouse2F" PARENT_SCOPE)
  elseif(constant_name STREQUAL "LAST_MAP")
    set(${out} "pokered::WorldId::RedsHouse1F" PARENT_SCOPE)
  else()
    message(FATAL_ERROR "Unsupported warp destination ${constant_name}")
  endif()
endfunction()

foreach(raw_line IN LISTS OBJECT_LINES)
  string(STRIP "${raw_line}" line)
  if(line MATCHES "^db \\$([0-9A-Fa-f]+)")
    string(TOUPPER "${CMAKE_MATCH_1}" BORDER_HEX)
    set(BORDER_BLOCK "0x${BORDER_HEX}")
  elseif(line MATCHES "^warp_event[ \t]+([0-9]+),[ \t]*([0-9]+),[ \t]*([A-Z0-9_]+),[ \t]*([0-9]+)")
    set(warp_x "${CMAKE_MATCH_1}")
    set(warp_y "${CMAKE_MATCH_2}")
    set(warp_destination "${CMAKE_MATCH_3}")
    set(warp_id "${CMAKE_MATCH_4}")
    if(warp_destination STREQUAL "LAST_MAP")
      set(uses_last_map "true")
    else()
      set(uses_last_map "false")
    endif()
    map_to_world_id(target_world_id "${warp_destination}")
    string(APPEND WARPS
           "    {${warp_x}, ${warp_y}, ${uses_last_map}, ${target_world_id}, ${warp_id}},\n")
    math(EXPR WARP_COUNT "${WARP_COUNT} + 1")
  elseif(line MATCHES "^bg_event[ \t]+([0-9]+),[ \t]*([0-9]+),[ \t]*TEXT_REDSHOUSE1F_TV")
    string(APPEND BG_EVENTS
           "    {${CMAKE_MATCH_1}, ${CMAKE_MATCH_2}, pokered::MessageId::TvMovie},\n")
    math(EXPR BG_EVENT_COUNT "${BG_EVENT_COUNT} + 1")
  elseif(line MATCHES "^object_event[ \t]+([0-9]+),[ \t]*([0-9]+),[ \t]*SPRITE_[A-Z0-9_]+,[ \t]*STAY,[ \t]*([A-Z]+),[ \t]*TEXT_REDSHOUSE1F_MOM")
    set(facing_token "${CMAKE_MATCH_3}")
    if(facing_token STREQUAL "UP")
      set(facing "pokered::Facing::Up")
    elseif(facing_token STREQUAL "DOWN")
      set(facing "pokered::Facing::Down")
    elseif(facing_token STREQUAL "LEFT")
      set(facing "pokered::Facing::Left")
    elseif(facing_token STREQUAL "RIGHT")
      set(facing "pokered::Facing::Right")
    else()
      message(FATAL_ERROR "Unsupported facing token: ${facing_token}")
    endif()
    string(APPEND NPCS
           "    {${CMAKE_MATCH_1}, ${CMAKE_MATCH_2}, ${facing}, pokered::MessageId::MomWakeUp},\n")
    math(EXPR NPC_COUNT "${NPC_COUNT} + 1")
  endif()
endforeach()

set(IN_REDS_HOUSE_COLL FALSE)
foreach(raw_line IN LISTS COLLISION_LINES)
  string(STRIP "${raw_line}" line)
  if(line STREQUAL "RedsHouse1_Coll::" OR line STREQUAL "RedsHouse2_Coll::")
    set(IN_REDS_HOUSE_COLL TRUE)
  elseif(IN_REDS_HOUSE_COLL AND line MATCHES "^coll_tiles")
    string(REGEX MATCHALL "\\$[0-9A-Fa-f][0-9A-Fa-f]" collision_matches "${line}")
    foreach(match IN LISTS collision_matches)
      string(SUBSTRING "${match}" 1 2 collision_hex)
      string(TOUPPER "${collision_hex}" collision_hex)
      string(APPEND COLLISION_TILES "    0x${collision_hex},\n")
      math(EXPR COLLISION_TILE_COUNT "${COLLISION_TILE_COUNT} + 1")
    endforeach()
    set(IN_REDS_HOUSE_COLL FALSE)
  endif()
endforeach()

if(COLLISION_TILE_COUNT EQUAL 0)
  message(FATAL_ERROR "Failed to parse RedsHouse1 collision tiles from ${COLLISION_FILE}")
endif()

set(CURRENT_NAME "")
set(CURRENT_TEXT "")
set(MESSAGE_NAMES "")

foreach(raw_line IN LISTS TEXT_LINES)
  string(STRIP "${raw_line}" line)
  if(line MATCHES "^_([A-Za-z0-9_]+)::")
    set(CURRENT_NAME "${CMAKE_MATCH_1}")
    set(CURRENT_TEXT "")
  elseif(line MATCHES "^(text|line|cont|para) \"(.*)\"$")
    set(command_name "${CMAKE_MATCH_1}")
    set(chunk "${CMAKE_MATCH_2}")
    if(command_name STREQUAL "text")
      set(CURRENT_TEXT "${chunk}")
    elseif(command_name STREQUAL "para")
      string(APPEND CURRENT_TEXT "${PAGE_BREAK_MARKER}${chunk}")
    else()
      string(APPEND CURRENT_TEXT "\n${chunk}")
    endif()
  elseif(line STREQUAL "done" OR line STREQUAL "prompt")
    if(NOT CURRENT_NAME STREQUAL "")
      string(REPLACE "<PLAYER>" "PLAYER" CURRENT_TEXT "${CURRENT_TEXT}")
      list(APPEND MESSAGE_NAMES "${CURRENT_NAME}")
      set("TEXT_${CURRENT_NAME}" "${CURRENT_TEXT}")
      set(CURRENT_NAME "")
      set(CURRENT_TEXT "")
    endif()
  endif()
endforeach()

file(WRITE "${OUTPUT}" "#pragma once\n\n#include <array>\n#include <cstdint>\n#include <string_view>\n\n#include \"pokered/world/map_data.hpp\"\n\nnamespace generated {\ninline constexpr std::uint8_t kRedsHouse1FBorderBlock = ${BORDER_BLOCK};\ninline constexpr std::array<pokered::Warp, ${WARP_COUNT}> kRedsHouse1FWarps = {{\n${WARPS}}};\ninline constexpr std::array<pokered::BgEvent, ${BG_EVENT_COUNT}> kRedsHouse1FBgEvents = {{\n${BG_EVENTS}}};\ninline constexpr std::array<pokered::Npc, ${NPC_COUNT}> kRedsHouse1FNpcs = {{\n${NPCS}}};\n")
file(APPEND "${OUTPUT}" "inline constexpr std::array<std::uint8_t, ${COLLISION_TILE_COUNT}> kRedsHouseCollisionTiles = {{\n${COLLISION_TILES}}};\n")

foreach(message_name IN LISTS MESSAGE_NAMES)
  escape_cpp(escaped_text "${TEXT_${message_name}}")
  file(APPEND "${OUTPUT}"
       "inline constexpr std::string_view k${message_name} = \"${escaped_text}\";\n")
endforeach()

file(APPEND "${OUTPUT}" "}  // namespace generated\n")
