if(NOT DEFINED OBJECTS_FILE OR NOT DEFINED OUTPUT)
  message(FATAL_ERROR "OBJECTS_FILE and OUTPUT must be provided")
endif()

file(STRINGS "${OBJECTS_FILE}" OBJECT_LINES)

function(map_to_world_id out constant_name)
  if(constant_name STREQUAL "REDS_HOUSE_1F")
    set(${out} "pokered::WorldId::RedsHouse1F" PARENT_SCOPE)
  elseif(constant_name STREQUAL "REDS_HOUSE_2F")
    set(${out} "pokered::WorldId::RedsHouse2F" PARENT_SCOPE)
  elseif(constant_name STREQUAL "LAST_MAP")
    set(${out} "pokered::WorldId::RedsHouse1F" PARENT_SCOPE)
  else()
    message(FATAL_ERROR "Unsupported warp destination ${constant_name}")
  endif()
endfunction()

set(BORDER_BLOCK "0x00")
set(WARP_COUNT 0)
set(WARPS "")

foreach(raw_line IN LISTS OBJECT_LINES)
  string(STRIP "${raw_line}" line)
  if(line MATCHES "^db \\$([0-9A-Fa-f]+)")
    string(TOUPPER "${CMAKE_MATCH_1}" border_hex)
    set(BORDER_BLOCK "0x${border_hex}")
  elseif(line MATCHES "^warp_event[ \t]+([0-9]+),[ \t]*([0-9]+),[ \t]*([A-Z0-9_]+),[ \t]*([0-9]+)")
    set(warp_x "${CMAKE_MATCH_1}")
    set(warp_y "${CMAKE_MATCH_2}")
    set(warp_destination "${CMAKE_MATCH_3}")
    set(warp_id "${CMAKE_MATCH_4}")
    if(warp_destination STREQUAL "LAST_MAP")
      set(uses_last_map "true")
    else()
      set(uses_last_map "false")
    endif()
    map_to_world_id(target_world_id "${warp_destination}")
    string(APPEND WARPS
           "    {${warp_x}, ${warp_y}, ${uses_last_map}, ${target_world_id}, ${warp_id}},\n")
    math(EXPR WARP_COUNT "${WARP_COUNT} + 1")
  endif()
endforeach()

file(WRITE "${OUTPUT}" "#pragma once\n\n#include <array>\n#include <cstdint>\n\n#include \"pokered/world/map_data.hpp\"\n\nnamespace generated {\ninline constexpr std::uint8_t kRedsHouse2FBorderBlock = ${BORDER_BLOCK};\ninline constexpr std::array<pokered::Warp, ${WARP_COUNT}> kRedsHouse2FWarps = {{\n${WARPS}}};\ninline constexpr std::array<pokered::BgEvent, 0> kRedsHouse2FBgEvents = {};\ninline constexpr std::array<pokered::Npc, 0> kRedsHouse2FNpcs = {};\n}  // namespace generated\n")
